Traceback (most recent call last):
  File "init.py", line 9, in <module>
    conn = sqlite3.connect(os.path.join(DATA_DIR,"faceembedding.db"))
sqlite3.OperationalError: unable to open database file
Init process failed to start exit status 1bash: redis-server: command not found
